### ISSUE TITLE
Incompatibility with newer versions of semantic release and commit analyzer

### ISSUE THREAD

**Issue by evelynhathaway** [evelynhathaway/commit-analyzer-fail-on-no-release#150]
I received this email and documenting it GitHub to keep track of it better. I anticipate this error is from breaking changes in semantic-release and commit-analyzer.

> Hello Evelyn,
> 
> First of all I would like to say thank you for creating this plugin (https://github.com/evelynhathaway/commit-analyzer-fail-on-no-release)! :)
> 
> Recently I faced an issue with semantic-release which your plugin may help to resolve.
Unfortunately, I am facing the following error when I try to use it:
> 
> ```
> [semantic-release --plugins commit-analyzer-fail-on-no-release]
> The plugins (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#plugins) option must be an array of plugin definitions. A plugin definition is an npm module name, optionally wrapped in an array with an object.
> 
> The invalid configuration is [Module: null prototype] { analyzeCommits: [AsyncFunction: analyzeCommits] }.
> 
> AggregateError:
>     SemanticReleaseError: The `plugins` configuration is invalid.
>         at default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/get-error.js:6:10)
>         at file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/plugins/index.js:32:25
>         at async default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/plugins/index.js:14:7)
>         at async default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/get-config.js:92:30)
>         at async Module.default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/index.js:274:34)
>         at async default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/cli.js:55:5)
>     at default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/plugins/index.js:43:11)
>     at async default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/get-config.js:92:30)
>     at async Module.default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/index.js:274:34)
>     at async default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/cli.js:55:5) {
>   errors: [
>     SemanticReleaseError: The `plugins` configuration is invalid.
>         at default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/get-error.js:6:10)
>         at file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/plugins/index.js:32:25
>         at async default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/plugins/index.js:14:7)
>         at async default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/get-config.js:92:30)
>         at async Module.default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/index.js:274:34)
>         at async default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/cli.js:55:5) {
>       code: 'EPLUGINSCONF',
>       details: 'The [plugins](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#plugins) option must be an array of plugin definitions. A plugin definition is an npm module name, optionally wrapped in an array with an object.\n' +
>         '\n' +
>         'The invalid configuration is `[Module: null prototype] { analyzeCommits: [AsyncFunction: analyzeCommits] }`.',
>       semanticRelease: true
>     }
>   ]
> }
> ```
> 
> AND
> 
> ```
> [semantic-release --no-ci --analyze-commits commit-analyzer-fail-on-no-release]
> A valid analyzeCommits semantic-release plugin must be a function or an object with a function in the property analyzeCommits.
> 
> The plugin commit-analyzer-fail-on-no-release doesn't have the property analyzeCommits and cannot be used for the analyzeCommits step.
> 
> Please refer to the commit-analyzer-fail-on-no-release and semantic-release plugins configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/plugins.md) documentation for more details.
> 
> SemanticReleaseError: A plugin configured in the step analyzeCommits is not a valid semantic-release plugin.
>     at default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/get-error.js:6:10)
>     at default (file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/plugins/normalize.js:28:11)
>     at async Promise.all (index 0)
>     at async file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/plugins/index.js:74:21
>     at async file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/plugins/index.js:54:40
>     at async file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/plugins/index.js:54:40
>     at async file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/plugins/index.js:54:40
>     at async file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/plugins/index.js:54:40
>     at async file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/plugins/index.js:54:40
>     at async file:///usr/local/share/.config/yarn/global/node_modules/semantic-release/lib/plugins/index.js:54:40 {
>   code: 'EPLUGIN',
>   details: 'A valid `analyzeCommits` **semantic-release** plugin must be a function or an object with a function in the property `analyzeCommits`.\n' +
>     '\n' +
>     "The plugin `commit-analyzer-fail-on-no-release` doesn't have the property `analyzeCommits` and cannot be used for the `analyzeCommits` step.\n" +
>     '\n' +
>     'Please refer to the `commit-analyzer-fail-on-no-release` and [semantic-release plugins configuration](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/plugins.md) documentation for more details.',
>   semanticRelease: true
> }
> ```
> 
> My semantic-release version is 24.2.0.
> 
> Сould you please advise how this can be fixed?

**Comment by evelynhathaway** [comment]
Currently, we only support v8 and v9 of commit-analyzer:
https://github.com/evelynhathaway/commit-analyzer-fail-on-no-release/blob/02b200bc761127b8819478e68e46198a813b4f2a/package.json#L59C5-L59C60

And commit-analyzer v10 raises the semantic-release peer to v20.1.0, which leads me to believe significant changes were made since I last updated this plugin.

https://github.com/semantic-release/commit-analyzer/releases/tag/v10.0.0#:~:text=deps%3A%20raised%20the%20peer%2Ddependency%20requirement%20on%20semantic%2Drelease%20to%20v20.1.0

**Comment by evelynhathaway** [comment]
> Thank you for the kind words and the detailed report!
> 
> Unfortunately, I think this has something to do with your recent versions of semantic-release and @semantic-release/commit-analyzer. I haven't had a chance to update the plugin to behave like @semantic-release/commit-analyzer v10+, and those errors lead me to believe I need to do that.
> What you can try is downgrading @semantic-release/commit-analyzer to v9, and semantic-release to v18, which are known to be a good combination. If you'd like to stay on the later versions, you may have to wait on using this plugin until I get a chance to tackle this issue or submit a pull request for the issue.
> 
> I've [created a GitHub issue](https://github.com/evelynhathaway/commit-analyzer-fail-on-no-release/issues/150) to keep this on my radar. Sorry about your troubles! 
> 
> Happy coding,
> Evelyn

**Comment by evelynhathaway** [comment]
> And commit-analyzer v10 raises the semantic-release peer to v20.1.0, which leads me to believe significant changes were made since I last updated this plugin.

Yup! One of the few things that can break this plugin is commit analyzer switching to ESM, which they did in v10.

I've updated to plugin to proxy a single named export and use ESM in [v2.0.0](https://github.com/evelynhathaway/commit-analyzer-fail-on-no-release/releases/tag/v2.0.0), which should fix this issue.
